language: php
php:
  - 5.4
  - 5.5
env:
  - SYMFONY_VERSION="2.1.*"
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.7.*"
cache:
  directories:
    - vendor
    - bin
services:
  - mysql
install:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - composer require symfony/http-foundation:${SYMFONY_VERSION}
  - composer install --no-interaction
script:
  - phpcs
  - ./bin/phpunit

